openapi: "3.0.3"
info:
  description: "This is a doc practice for strive eventbrite project"
  version: "1.0.0"
  title: "Strive-Eventbrite"
  contact:
    email: "hungjinchong@outlook.com"
tags:
  - name: "attendees"
    description: "Everything about attendees"
paths:
  /attendees:
    post:
      tags:
        - "attendees"
      summary: "Add an attendees"
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Attendee"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
        "400":
          description: Bad Request
          content:
            text/html:
              schema:
                type: string
                example: "Required fields missing"
        "404":
          description: Not Found
          content:
            text/html:
              schema:
                type: string
                example: "Attendee Not Found"
        "500":
          description: Generic Server Error
          content:
            text/html:
              schema:
                type: string
                example: "Generic Server Error"
  /attendees/csv:
    get:
      tags:
        - csv
      summary: "Downloads a csv file"
      description: "Downloads a csv file"
      responses:
        "200":
          description: Ok
          content:
            text/html:
              schema:
                type: string
                example: "CSV DOWNLOADED"
        "404":
          description: Not Found
          content:
            text/html:
              schema:
                type: string
                example: "File not found"
        "500":
          description: Generic Server Error
          content:
            text/html:
              schema:
                type: string
                example: "Generic Server Error"
components:
  schemas:
    Attendee:
      type: object
      properties:
        firstName:
          type: string
        secondName:
          type: string
        email:
          type: string
        arrivalTime:
          type: string
        _id:
          type: string
        createdAt:
          type: string
      required:
        - firstName
        - secondName
        - email
        - arrivalTime
